<?php

namespace Frontend\StringValueBundle\Repository;

/**
 * StringValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StringValueRepository extends \Doctrine\ORM\EntityRepository
{
}
