<?php

namespace Frontend\StringKeyBundle\Repository;

/**
 * StringKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StringKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
