string_value:
    resource: "@StringValueBundle/Controller/"
    type:     annotation
    prefix:   /

operating_system:
    resource: "@OperatingSystemBundle/Controller/"
    type:     annotation
    prefix:   /

lang_lang:
    resource: "@LangBundle/Controller/LangController.php"
    type:     annotation

project_project:
    resource: "@ProjectBundle/Controller/ProjectController.php"
    type:     annotation

translate_string:
    resource: "@TranslateStringBundle/Controller/"
    type:     annotation
    prefix:   /

string_key:
    resource: "@StringKeyBundle/Controller/"
    type:     annotation
    prefix:   /

lang:
    resource: "@LangBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

project:
    resource: "@ProjectBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"