<?php

namespace Frontend\TranslateStringBundle\Repository;

/**
 * TranslateStringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslateStringRepository extends \Doctrine\ORM\EntityRepository
{
}
