<?php

namespace CoreSystem\MainBundle\Repository;

/**
 * MainEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
